# Generated by Django 3.0.4 on 2021-01-05 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fallowing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fallowing',
            options={'verbose_name_plural': 'Takiplesme Sistemi'},
        ),
    ]
