# Generated by Django 3.0.4 on 2020-09-29 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'Gonderiler'},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='icerik',
            new_name='content',
        ),
    ]
