# Generated by Django 3.0.4 on 2020-10-06 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200929_2325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['id'], 'verbose_name_plural': 'Gonderiler'},
        ),
    ]
