# Generated by Django 3.0.4 on 2020-10-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(help_text='Kapak Fotoğrafı Yükleyınız', null=True, upload_to='', verbose_name='Resim'),
        ),
    ]
