# Generated by Django 3.0.4 on 2020-10-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20201021_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='default/default-photo.webp', help_text='Kapak Fotoğrafı Yükleyınız', null=True, upload_to='', verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='kategoriler',
            field=models.ManyToManyField(blank=True, null=True, related_name='blog', to='blog.Kategori'),
        ),
    ]
