# Generated by Django 3.0.4 on 2020-10-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20201022_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='default/default-photo.webp', help_text='Kapak Fotoğrafı Yükleyınız', null=True, upload_to='blog', verbose_name='Resim'),
        ),
    ]
