# Generated by Django 3.0.4 on 2020-10-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_blog_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='unique_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
