# Generated by Django 3.0.4 on 2020-10-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20201024_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='yayin_taslak',
            field=models.CharField(choices=[(None, 'Lütfen birini seçiniz!'), ('yayin', 'YAYIN'), ('taslak', 'TASLAK')], max_length=6, null=True),
        ),
    ]
