# Generated by Django 3.0.4 on 2020-11-30 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_blog_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Gonderiler'},
        ),
    ]
