# Generated by Django 3.0.4 on 2020-12-30 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_favoriteblog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteblog',
            options={'verbose_name_plural': 'Favorilere Eklenen Gönderiler'},
        ),
    ]
